import { useEffect, useState } from 'react';
import { Settings } from 'lucide-react';
import { Modal } from '@/components/ui/Modal';
import { loadPreferences, savePreferences, type AgentPreferences } from '@/api/preferences';
import { createSession, listSessions, type SessionSummary } from '@/api/sessions';
export function AgentSettings() {
  const [open, setOpen] = useState(false); const [preferences, setPreferences] = useState<AgentPreferences>(loadPreferences); const [sessions, setSessions] = useState<SessionSummary[]>([]);
  useEffect(() => { if (open) void listSessions().then(setSessions).catch(() => setSessions([])); }, [open]);
  return <><button type="button" title="Agent 设置" onClick={() => setOpen(true)} className="grid h-[30px] w-[30px] place-items-center rounded-sm text-text-tertiary hover:bg-surface-2"><Settings size={16} /></button><Modal open={open} onClose={() => setOpen(false)} title="Agent 设置" footer={<button type="button" onClick={() => { savePreferences(preferences); setOpen(false); }} className="h-control rounded-sm bg-blue-solid px-4 text-body-sm text-on-solid">保存</button>}><div className="space-y-4"><section><div className="flex items-center justify-between"><span className="text-body-sm text-text-secondary">会话</span><button type="button" onClick={() => { void createSession().then((session) => setSessions((items) => [session, ...items])); }} className="text-caption text-accent">新建</button></div><p className="m-0 mt-1 text-caption text-text-tertiary">{sessions.length ? `${sessions.length} 个已保存会话` : '暂无已保存会话'}</p></section><label className="block text-body-sm text-text-secondary">模型<input value={preferences.model} onChange={(event) => setPreferences({ ...preferences, model: event.target.value })} placeholder="默认模型" className="mt-1 block w-full rounded-sm border border-border-default bg-surface-1 p-2 text-text-primary" /></label><label className="block text-body-sm text-text-secondary">个性化指令<textarea value={preferences.personality} onChange={(event) => setPreferences({ ...preferences, personality: event.target.value })} placeholder="Agent 的回答偏好" className="mt-1 block w-full rounded-sm border border-border-default bg-surface-1 p-2 text-text-primary" /></label><label className="block text-body-sm text-text-secondary">MCP Connector 端点<input value={preferences.connectors[0]?.endpoint ?? ''} onChange={(event) => setPreferences({ ...preferences, connectors: event.target.value ? [{ name: 'default', endpoint: event.target.value }] : [] })} placeholder="https://…" className="mt-1 block w-full rounded-sm border border-border-default bg-surface-1 p-2 text-text-primary" /></label><p className="m-0 text-caption text-text-tertiary">Connector 元数据由宿主注册；此处只保存本地连接偏好，不会改变运行时权限。</p></div></Modal></>;
}
