"""Deterministic Chinese summaries for the official extension catalog."""

SKILL_SUMMARIES_ZH = {
    "aspnet-core": "构建、审查与升级 ASP.NET Core Web 应用",
    "chatgpt-apps": "开发结合 MCP 服务与组件界面的 ChatGPT 应用",
    "cli-creator": "根据 API 文档或现有工具创建可复用命令行程序",
    "define-goal": "将模糊意图整理为具体、可衡量的工作目标",
    "figma": "读取 Figma 设计信息、资源与变量并生成代码",
    "figma-code-connect-components": "建立 Figma 组件与代码组件的映射关系",
    "figma-create-design-system-rules": "为项目生成 Figma 到代码的设计系统规则",
    "figma-create-new-file": "创建新的 Figma 设计文件或 FigJam 白板",
    "figma-generate-design": "根据代码或描述在 Figma 中搭建完整页面",
    "figma-generate-library": "从代码库创建或更新专业 Figma 设计系统",
    "figma-implement-design": "将 Figma 设计高还原地实现为生产代码",
    "figma-use": "通过插件 API 在 Figma 中创建、编辑与检查设计",
    "gh-address-comments": "处理当前 GitHub 拉取请求中的评审意见",
    "gh-fix-ci": "排查并修复 GitHub Actions 中失败的 CI 检查",
    "hatch-pet": "制作、校验并打包 Codex 动画宠物素材",
    "jupyter-notebook": "创建或编辑用于实验、分析和教程的 Jupyter 笔记本",
    "linear": "管理 Linear 中的问题、项目与团队工作流",
    "migrate-to-codex": "将指令、技能、代理与 MCP 配置迁移到 Codex",
    "netlify-deploy": "通过 Netlify CLI 部署、托管与发布网站",
    "notion-knowledge-capture": "将对话和决策整理为结构化 Notion 知识页面",
    "notion-meeting-intelligence": "结合 Notion 上下文准备议程与会前材料",
    "notion-research-documentation": "检索 Notion 内容并汇总为带引用的研究文档",
    "notion-spec-to-implementation": "把 Notion 需求转化为实施计划、任务与进度",
    "openai-docs": "查询 OpenAI 官方文档并提供最新开发指导",
    "pdf": "读取、创建、编辑并检查 PDF 文档与页面排版",
    "playwright": "自动操作真实浏览器并调试网页交互流程",
    "playwright-interactive": "通过持久浏览器会话快速迭代调试网页界面",
    "render-deploy": "分析项目并生成配置以部署到 Render 云平台",
    "screenshot": "截取桌面、应用窗口或指定屏幕区域",
    "security-best-practices": "审查代码安全实践并给出针对性改进建议",
    "security-ownership-map": "基于 Git 历史分析敏感代码归属与人员风险",
    "security-threat-model": "识别代码库信任边界、攻击路径与缓解措施",
    "sentry": "只读查询 Sentry 事件并汇总近期生产故障",
    "speech": "将文本批量转换为旁白、语音提示或无障碍音频",
    "transcribe": "将音频或视频转写为文本并支持说话人区分",
    "vercel-deploy": "将应用或网站部署到 Vercel 并生成访问地址",
    "winui-app": "使用 C# 与 Windows App SDK 开发 WinUI 3 应用",
    "yeet": "一次完成代码暂存、提交、推送与创建 GitHub PR",
    "docx": "创建、读取、编辑并专业排版 Word 文档",
    "pptx": "创建、读取、编辑与整理 PowerPoint 演示文稿",
    "xlsx": "创建、读取、清洗与分析电子表格文件",
}


CONNECTOR_DESCRIPTIONS_ZH = {
    "filesystem": "在授权目录内读取、搜索和管理本地文件与文件夹",
    "memory": "通过知识图谱保存实体、关系和跨会话上下文",
    "sequentialthinking": "用可调整的分步推理过程拆解和解决复杂问题",
    "fetch": "抓取网页内容并转换为便于模型阅读的结构化文本",
    "git": "读取与检查本地 Git 仓库的提交、分支和文件变更",
    "time": "查询时区时间并在不同地区之间进行时间换算",
    "github": "管理 GitHub 仓库、议题、拉取请求与代码协作流程",
    "playwright": "通过浏览器自动化访问网页、操作界面并提取内容",
}
